install:
#- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

platform:
- Win32
#- x64

configuration: Release

os :
#- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

matrix:
  allow_failures:
  - os: Visual Studio 2017

on_finish:
  - cd c:\
  - dir /s libcpmt.lib
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
